### ISSUE TITLE
Do you have a plan to support SweRV-EL2 ?

### ISSUE THREAD

**Issue by kidonglee** [chipsalliance/VeeRwolf#28]
Hi, 

It seems that Cores-SweRVolf currently supports only SweRV (EH1).
Do you have any plan to support SweRV-EL2.

Thanks.

**Comment by kidonglee** [comment]
I am sorry.
I found that Cores-SweRVolf support SwerRV-EL2, also.
I cloned el2 branch from git.
And I modified fusesoc.conf file to add the folder containing swerf_el2.conf to library.
Finally, I got FPGA bitstream though I have no Nexys_A7 board to test it.

BTW, there are some timing violation on the ibus clock (100MHz).
Is it OK?

**Comment by nicolast0604** [comment]
I am also wondering if Cores-SweRVolf support **SwerRV-EH2.**
If yes, could you please share me how to get it.

Thanks a lot.

**Comment by olofk** [comment]
My apologies. Completely missed this. Yes. EL2 support is basically done. Just needs final testing and it will be part of the next release. EH2 support is a bit further away. It will come eventuall but I can't guarantee when that will happen unfortunately.

**Comment by olofk** [comment]
Forgot to close this. EL2 is supported since 0.7.4
