### ISSUE TITLE
Updating wb_intercon

### ISSUE THREAD

**Issue by gsinside** [chipsalliance/VeeRwolf#72]
Can anyone tell me the right way to specify the latest version of wb_intercon (1.4.1) to override the one in the fusesoc core libraries?
I know I can add the library manually, but how can I get it to pull a specific repo automatically like it does for the VeeR-EL2 core?

I realize other changes are needed to migrate to the latest, but they are fairly straightforward and not difficult.

**Comment by gsinside** [comment]
I submitted a pull request to add wb_intercon v1.4.1 to fusesoc-cores.  I think this is the correct fix.
https://github.com/fusesoc/fusesoc-cores/pull/17

**Comment by olofk** [comment]
Yes! Thanks. I believe we're all good now
